### ISSUE TITLE
Subfolder navigation

### ISSUE THREAD

**Issue by justanickname** [libretro/Lakka#112]
Browsing is currently flat, which can make it harder to navigate to files you want to load. Let's say you have a bunch of anime series on your disk, and they are nicely organized into different subfolders (for example all Naruto episodes in /storage/roms/video/Naruto/, Hellsing in /storage/roms/video/Hellsing/, etc).

It would then be nicer if the Lakka user can see those subfolders and enter them like in the real XMB (if you have a PS3 you can try putting some compatible videos in different subfolders there to see what I mean), instead of having to navigate a flat structure with hundreds of random files.

**Comment by ProfessorKaos64** [comment]
I would like this as well. One of the nice things about Emulation Station, is it will present sub folders. I use this to my advantage, making A-B, C-D, E-F folders and so forth for MAME. If not, an enhancement to filter by letter would be nice.

**Comment by Kivutar** [comment]
In the latest development buids, you can use the "Load Content (Detect Core)" entry to browser everything by folders.

Generated playlists are still flat, but since we linked them to database stuff,  think it would make things complex to add subfolders for roms in playlists.

However, if we add special tabs for Videos, Images, and Music like on the real XMB, I will try to allow subfolder navigation in these.

**Comment by Kivutar** [comment]
The way media tabs were implemented won't allow directory browsing. So I close this as "won't fix".
