### ISSUE TITLE
Settings web interface

### ISSUE THREAD

**Issue by AntoineTurmel** [libretro/Lakka#129]
It would be nice to have web interface to manage Settings on another computer, juste like being able to copy file using netshare.

**Comment by Kivutar** [comment]
Now that our menu allows editing all settings, I don't think the web interface is needed anymore.

Also, it would be difficult to implement, since retroarch would override the changes. Unlike EmulationStation based distros, we keep retroarch launched 100% of the time. And it will override the retroarch.cfg with what it keeps in RAM.
