### ISSUE TITLE
[Enhancement] Show CPU Temp on Menu for Developer Boards

### ISSUE THREAD

**Issue by jayp76** [libretro/Lakka#175]
Show CPU Temp on Menu for Developer Boards, like Raspberry Pi.

**Comment by Kivutar** [comment]
Like dwm does, RetroArch could execute a user shell script while in the menu. This shell script could get the battery status, cpu usage, ip, and bake a parsable list, to be displayed with the file_list api.

**Comment by Kivutar** [comment]
Due to my lack of motivation to implement this, and the refusal from libretro to go the "script way", I close this.

You can still post a feature request on RetroArch issue tracker. RetroArch is displaying more and more informations from the underlaying OS in the System Informations menu. So it could be done too.
