### ISSUE TITLE
PPSSPP Segfault

### ISSUE THREAD

**Issue by lollo78** [libretro/Lakka#254]
Hi, ppsspp_libretro.so down't work for me.
If I try to launch from shell I see the error Segmentation fault.

**Comment by lollo78** [comment]
I forgot to specify that I use a Raspberry Pi 2.

**Comment by Kivutar** [comment]
Are you using the latest release? I tested ppsspp on rpi2 myself so it should work.

**Comment by lollo78** [comment]
Yes, the latest

**Comment by Kivutar** [comment]
Hi @lollo78 
I just tested the latest release with PPSSPP on the RPi2, with the Flow game. And it worked.

**Comment by Kivutar** [comment]
You tried with many ROMs? I'm not able to reproduce this bug.

**Comment by lollo78** [comment]
I tried with other roms (also in cso format) and I can confirm that PPSSPP works. 
But on Rpi2 it's very very slow (what a pity)

**Comment by Kivutar** [comment]
Try to enable all the speed hacks. And choose a light game like FF3. Anyway, we can close this now since it doesn't segfault anymore.

If you want to improve performance, you can declare a bug in PPSSPP libretro repo. Ask them to fix the non buffered rendering. This option is broken, and can improve performance.

**Comment by lollo78** [comment]
Ok, Thx. But this feature is broken only for rpi2?

**Comment by Kivutar** [comment]
No, it's broken in all platforms for ppsspp-libretro.

**Comment by lollo78** [comment]
OK, I opened an issue on the PPSSP libretro core github.
I really hope for a fix.
It could be so nice...
